### ISSUE TITLE
Not possible to set breakpoint using slime-line-breakpoint

### ISSUE THREAD

**Issue by jbeh** [pallet/ritz#18]
Calling slime-line-breakpoint from a debugged clj buffer in emacs leads to the following error:

lein ritz
user=> Swank server listening on local port  4005
user=> clojure.lang.ArityException: Wrong number of args (1) passed to: jdi$namespace-classes
        at clojure.lang.AFn.throwArity(AFn.java:437)
        at clojure.lang.AFn.invoke(AFn.java:39)
        at ritz.jpda.jdi$file_classes.invoke(jdi.clj:292)
        at ritz.jpda.jdi$line_breakpoints.invoke(jdi.clj:434)
        at ritz.jpda.debug$line_breakpoint.invoke(debug.clj:352)
        at clojure.lang.AFn.applyToHelper(AFn.java:172)
        at clojure.lang.AFn.applyTo(AFn.java:151)
        at clojure.lang.Atom.swap(Atom.java:79)
        at clojure.core$swap_BANG_.doInvoke(core.clj:2109)
        at clojure.lang.RestFn.invoke(RestFn.java:497)
        at ritz.commands.contrib.ritz$line_breakpoint.invoke(ritz.clj:23)
        at clojure.lang.Var.invoke(Var.java:413)
        at clojure.lang.AFn.applyToHelper(AFn.java:172)
        at clojure.lang.Var.applyTo(Var.java:518)
        at clojure.core$apply.invoke(core.clj:602)
        at ritz.swank.core$execute_slime_fn_STAR_.invoke(core.clj:86)
        at ritz.jpda.debug$execute_unless_inspect$fn__1590.invoke(debug.clj:199)
        at ritz.jpda.debug$execute_inspect_if_inspector_active$fn__1576.invoke(debug.clj:180)
        at ritz.jpda.debug$execute_if_inspect_frame_var$fn__1572.invoke(debug.clj:166)
        at ritz.swank$eval_for_emacs.invoke(swank.clj:32)
        at ritz.swank$dispatch_event.invoke(swank.clj:107)
        at ritz.swank$handle_message$fn__2276.invoke(swank.clj:191)
        at clojure.lang.AFn.call(AFn.java:18)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
        at java.util.concurrent.FutureTask.run(FutureTask.java:138)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
        at java.lang.Thread.run(Thread.java:662)

**Comment by hugoduncan** [comment]
Apologies, looks like I missed this issue. I have fixed a couple of things in this area in 0.3.0-SNAPSHOT. Given the age of this issue, I am going to close, but please feel free to reopen if you are still having issues.
