### ISSUE TITLE
clojure-jack-in wont work in 0.4.0.

### ISSUE THREAD

**Issue by cola-zero** [pallet/ritz#31]
When I use ritz-0.4.0, M-x clojure-jack-in won't work.
Here is *Backtrace*,

```
;;; Bootstrapping bundled version of SLIME; please wait...


java.lang.IllegalArgumentException: No implementation of method: :make-reader of protocol: #'clojure.java.io/IOFactory found for class: nil
    at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:527)
    at clojure.java.io$fn__8239$G__8234__8246.invoke(io.clj:73)
    at clojure.java.io$reader.doInvoke(io.clj:106)
    at clojure.lang.RestFn.invoke(RestFn.java:410)
    at clojure.lang.AFn.applyToHelper(AFn.java:161)
    at clojure.lang.RestFn.applyTo(RestFn.java:132)
    at clojure.core$apply.invoke(core.clj:603)
    at clojure.core$slurp.doInvoke(core.clj:6126)
    at clojure.lang.RestFn.invoke(RestFn.java:410)
    at leiningen.ritz_in$hex_digest.invoke(ritz_in.clj:20)
    at leiningen.ritz_in$loader.invoke(ritz_in.clj:24)
    at clojure.core$map$fn__4087.invoke(core.clj:2434)
    at clojure.lang.LazySeq.sval(LazySeq.java:42)
    at clojure.lang.LazySeq.seq(LazySeq.java:60)
    at clojure.lang.Cons.next(Cons.java:39)
    at clojure.lang.LazySeq.next(LazySeq.java:92)
    at clojure.lang.RT.next(RT.java:587)
    at clojure.core$next.invoke(core.clj:64)
    at clojure.string$join.invoke(string.clj:138)
    at leiningen.ritz_in$ritz_in.invoke(ritz_in.clj:53)
    at clojure.lang.Var.invoke(Var.java:419)
    at clojure.lang.AFn.applyToHelper(AFn.java:163)
    at clojure.lang.Var.applyTo(Var.java:532)
    at clojure.core$apply.invoke(core.clj:603)
    at leiningen.core.main$resolve_task$fn__823.doInvoke(main.clj:73)
    at clojure.lang.RestFn.applyTo(RestFn.java:139)
    at clojure.lang.AFunction$1.doInvoke(AFunction.java:29)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:603)
    at leiningen.core.main$apply_task.invoke(main.clj:95)
    at leiningen.core.main$_main$fn__862.invoke(main.clj:156)
    at leiningen.core.main$_main.doInvoke(main.clj:155)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at clojure.lang.Var.invoke(Var.java:419)
    at clojure.lang.AFn.applyToHelper(AFn.java:163)
    at clojure.lang.Var.applyTo(Var.java:532)
    at clojure.core$apply.invoke(core.clj:601)
    at clojure.main$main_opt.invoke(main.clj:324)
    at clojure.main$main.doInvoke(main.clj:427)
    at clojure.lang.RestFn.invoke(RestFn.java:457)
    at clojure.lang.Var.invoke(Var.java:427)
    at clojure.lang.AFn.applyToHelper(AFn.java:172)
    at clojure.lang.Var.applyTo(Var.java:532)
    at clojure.main.main(main.java:37)
")
  signal(error ("Could not start swank server: ;;; Bootstrapping bundled version of SLIME; please wait...\n\n\njava.lang.IllegalArgumentException: No implementation of method: :make-reader of protocol: #'clojure.java.io/IOFactory found for class: nil\n    at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:527)\n   at clojure.java.io$fn__8239$G__8234__8246.invoke(io.clj:73)\n   at clojure.java.io$reader.doInvoke(io.clj:106)\n    at clojure.lang.RestFn.invoke(RestFn.java:410)\n    at clojure.lang.AFn.applyToHelper(AFn.java:161)\n   at clojure.lang.RestFn.applyTo(RestFn.java:132)\n   at clojure.core$apply.invoke(core.clj:603)\n    at clojure.core$slurp.doInvoke(core.clj:6126)\n at clojure.lang.RestFn.invoke(RestFn.java:410)\n    at leiningen.ritz_in$hex_digest.invoke(ritz_in.clj:20)\n    at leiningen.ritz_in$loader.invoke(ritz_in.clj:24)\n    at clojure.core$map$fn__4087.invoke(core.clj:2434)\n    at clojure.lang.LazySeq.sval(LazySeq.java:42)\n at clojure.lang.LazySeq.seq(LazySeq.java:60)\n  at clojure.lang.Cons.next(Cons.java:39)\n   at clojure.lang.LazySeq.next(LazySeq.java:92)\n at clojure.lang.RT.next(RT.java:587)\n  at clojure.core$next.invoke(core.clj:64)\n  at clojure.string$join.invoke(string.clj:138)\n at leiningen.ritz_in$ritz_in.invoke(ritz_in.clj:53)\n   at clojure.lang.Var.invoke(Var.java:419)\n  at clojure.lang.AFn.applyToHelper(AFn.java:163)\n   at clojure.lang.Var.applyTo(Var.java:532)\n at clojure.core$apply.invoke(core.clj:603)\n    at leiningen.core.main$resolve_task$fn__823.doInvoke(main.clj:73)\n at clojure.lang.RestFn.applyTo(RestFn.java:139)\n   at clojure.lang.AFunction$1.doInvoke(AFunction.java:29)\n   at clojure.lang.RestFn.applyTo(RestFn.java:137)\n   at clojure.core$apply.invoke(core.clj:603)\n    at leiningen.core.main$apply_task.invoke(main.clj:95)\n at leiningen.core.main$_main$fn__862.invoke(main.clj:156)\n at leiningen.core.main$_main.doInvoke(main.clj:155)\n   at clojure.lang.RestFn.invoke(RestFn.java:421)\n    at clojure.lang.Var.invoke(Var.java:419)\n  at clojure.lang.AFn.applyToHelper(AFn.java:163)\n   at clojure.lang.Var.applyTo(Var.java:532)\n at clojure.core$apply.invoke(core.clj:601)\n    at clojure.main$main_opt.invoke(main.clj:324)\n at clojure.main$main.doInvoke(main.clj:427)\n   at clojure.lang.RestFn.invoke(RestFn.java:457)\n    at clojure.lang.Var.invoke(Var.java:427)\n  at clojure.lang.AFn.applyToHelper(AFn.java:172)\n   at clojure.lang.Var.applyTo(Var.java:532)\n at clojure.main.main(main.java:37)\n;;; Bootstrapping bundled version of SLIME; please wait...\n\n\njava.lang.IllegalArgumentException: No implementation of method: :make-reader of protocol: #'clojure.java.io/IOFactory found for class: nil\n   at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:527)\n   at clojure.java.io$fn__8239$G__8234__8246.invoke(io.clj:73)\n   at clojure.java.io$reader.doInvoke(io.clj:106)\n    at clojure.lang.RestFn.invoke(RestFn.java:410)\n    at clojure.lang.AFn.applyToHelper(AFn.java:161)\n   at clojure.lang.RestFn.applyTo(RestFn.java:132)\n   at clojure.core$apply.invoke(core.clj:603)\n    at clojure.core$slurp.doInvoke(core.clj:6126)\n at clojure.lang.RestFn.invoke(RestFn.java:410)\n    at leiningen.ritz_in$hex_digest.invoke(ritz_in.clj:20)\n    at leiningen.ritz_in$loader.invoke(ritz_in.clj:24)\n    at clojure.core$map$fn__4087.invoke(core.clj:2434)\n    at clojure.lang.LazySeq.sval(LazySeq.java:42)\n at clojure.lang.LazySeq.seq(LazySeq.java:60)\n  at clojure.lang.Cons.next(Cons.java:39)\n   at clojure.lang.LazySeq.next(LazySeq.java:92)\n at clojure.lang.RT.next(RT.java:587)\n  at clojure.core$next.invoke(core.clj:64)\n  at clojure.string$join.invoke(string.clj:138)\n at leiningen.ritz_in$ritz_in.invoke(ritz_in.clj:53)\n   at clojure.lang.Var.invoke(Var.java:419)\n  at clojure.lang.AFn.applyToHelper(AFn.java:163)\n   at clojure.lang.Var.applyTo(Var.java:532)\n at clojure.core$apply.invoke(core.clj:603)\n    at leiningen.core.main$resolve_task$fn__823.doInvoke(main.clj:73)\n at clojure.lang.RestFn.applyTo(RestFn.java:139)\n   at clojure.lang.AFunction$1.doInvoke(AFunction.java:29)\n   at clojure.lang.RestFn.applyTo(RestFn.java:137)\n   at clojure.core$apply.invoke(core.clj:603)\n    at leiningen.core.main$apply_task.invoke(main.clj:95)\n at leiningen.core.main$_main$fn__862.invoke(main.clj:156)\n at leiningen.core.main$_main.doInvoke(main.clj:155)\n   at clojure.lang.RestFn.invoke(RestFn.java:421)\n    at clojure.lang.Var.invoke(Var.java:419)\n  at clojure.lang.AFn.applyToHelper(AFn.java:163)\n   at clojure.lang.Var.applyTo(Var.java:532)\n at clojure.core$apply.invoke(core.clj:601)\n    at clojure.main$main_opt.invoke(main.clj:324)\n at clojure.main$main.doInvoke(main.clj:427)\n   at clojure.lang.RestFn.invoke(RestFn.java:457)\n    at clojure.lang.Var.invoke(Var.java:427)\n  at clojure.lang.AFn.applyToHelper(AFn.java:172)\n   at clojure.lang.Var.applyTo(Var.java:532)\n at clojure.main.main(main.java:37)\n;;; Bootstrapping bundled version of SLIME; please wait...\n\n\njava.lang.IllegalArgumentException: No implementation of method: :make-reader of protocol: #'clojure.java.io/IOFactory found for class: nil\n   at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:527)\n   at clojure.java.io$fn__8239$G__8234__8246.invoke(io.clj:73)\n   at clojure.java.io$reader.doInvoke(io.clj:106)\n    at clojure.lang.RestFn.invoke(RestFn.java:410)\n    at clojure.lang.AFn.applyToHelper(AFn.java:161)\n   at clojure.lang.RestFn.applyTo(RestFn.java:132)\n   at clojure.core$apply.invoke(core.clj:603)\n    at clojure.core$slurp.doInvoke(core.clj:6126)\n at clojure.lang.RestFn.invoke(RestFn.java:410)\n    at leiningen.ritz_in$hex_digest.invoke(ritz_in.clj:20)\n    at leiningen.ritz_in$loader.invoke(ritz_in.clj:24)\n    at clojure.core$map$fn__4087.invoke(core.clj:2434)\n    at clojure.lang.LazySeq.sval(LazySeq.java:42)\n at clojure.lang.LazySeq.seq(LazySeq.java:60)\n  at clojure.lang.Cons.next(Cons.java:39)\n   at clojure.lang.LazySeq.next(LazySeq.java:92)\n at clojure.lang.RT.next(RT.java:587)\n  at clojure.core$next.invoke(core.clj:64)\n  at clojure.string$join.invoke(string.clj:138)\n at leiningen.ritz_in$ritz_in.invoke(ritz_in.clj:53)\n   at clojure.lang.Var.invoke(Var.java:419)\n  at clojure.lang.AFn.applyToHelper(AFn.java:163)\n   at clojure.lang.Var.applyTo(Var.java:532)\n at clojure.core$apply.invoke(core.clj:603)\n    at leiningen.core.main$resolve_task$fn__823.doInvoke(main.clj:73)\n at clojure.lang.RestFn.applyTo(RestFn.java:139)\n   at clojure.lang.AFunction$1.doInvoke(AFunction.java:29)\n   at clojure.lang.RestFn.applyTo(RestFn.java:137)\n   at clojure.core$apply.invoke(core.clj:603)\n    at leiningen.core.main$apply_task.invoke(main.clj:95)\n at leiningen.core.main$_main$fn__862.invoke(main.clj:156)\n at leiningen.core.main$_main.doInvoke(main.clj:155)\n   at clojure.lang.RestFn.invoke(RestFn.java:421)\n    at clojure.lang.Var.invoke(Var.java:419)\n  at clojure.lang.AFn.applyToHelper(AFn.java:163)\n   at clojure.lang.Var.applyTo(Var.java:532)\n at clojure.core$apply.invoke(core.clj:601)\n    at clojure.main$main_opt.invoke(main.clj:324)\n at clojure.main$main.doInvoke(main.clj:427)\n   at clojure.lang.RestFn.invoke(RestFn.java:457)\n    at clojure.lang.Var.invoke(Var.java:427)\n  at clojure.lang.AFn.applyToHelper(AFn.java:172)\n   at clojure.lang.Var.applyTo(Var.java:532)\n at clojure.main.main(main.java:37)\n"))
  error("Could not start swank server: %s" ";;; Bootstrapping bundled version of SLIME; please wait...\n\n\njava.lang.IllegalArgumentException: No implementation of method: :make-reader of protocol: #'clojure.java.io/IOFactory found for class: nil\n   at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:527)\n   at clojure.java.io$fn__8239$G__8234__8246.invoke(io.clj:73)\n   at clojure.java.io$reader.doInvoke(io.clj:106)\n    at clojure.lang.RestFn.invoke(RestFn.java:410)\n    at clojure.lang.AFn.applyToHelper(AFn.java:161)\n   at clojure.lang.RestFn.applyTo(RestFn.java:132)\n   at clojure.core$apply.invoke(core.clj:603)\n    at clojure.core$slurp.doInvoke(core.clj:6126)\n at clojure.lang.RestFn.invoke(RestFn.java:410)\n    at leiningen.ritz_in$hex_digest.invoke(ritz_in.clj:20)\n    at leiningen.ritz_in$loader.invoke(ritz_in.clj:24)\n    at clojure.core$map$fn__4087.invoke(core.clj:2434)\n    at clojure.lang.LazySeq.sval(LazySeq.java:42)\n at clojure.lang.LazySeq.seq(LazySeq.java:60)\n  at clojure.lang.Cons.next(Cons.java:39)\n   at clojure.lang.LazySeq.next(LazySeq.java:92)\n at clojure.lang.RT.next(RT.java:587)\n  at clojure.core$next.invoke(core.clj:64)\n  at clojure.string$join.invoke(string.clj:138)\n at leiningen.ritz_in$ritz_in.invoke(ritz_in.clj:53)\n   at clojure.lang.Var.invoke(Var.java:419)\n  at clojure.lang.AFn.applyToHelper(AFn.java:163)\n   at clojure.lang.Var.applyTo(Var.java:532)\n at clojure.core$apply.invoke(core.clj:603)\n    at leiningen.core.main$resolve_task$fn__823.doInvoke(main.clj:73)\n at clojure.lang.RestFn.applyTo(RestFn.java:139)\n   at clojure.lang.AFunction$1.doInvoke(AFunction.java:29)\n   at clojure.lang.RestFn.applyTo(RestFn.java:137)\n   at clojure.core$apply.invoke(core.clj:603)\n    at leiningen.core.main$apply_task.invoke(main.clj:95)\n at leiningen.core.main$_main$fn__862.invoke(main.clj:156)\n at leiningen.core.main$_main.doInvoke(main.clj:155)\n   at clojure.lang.RestFn.invoke(RestFn.java:421)\n    at clojure.lang.Var.invoke(Var.java:419)\n  at clojure.lang.AFn.applyToHelper(AFn.java:163)\n   at clojure.lang.Var.applyTo(Var.java:532)\n at clojure.core$apply.invoke(core.clj:601)\n    at clojure.main$main_opt.invoke(main.clj:324)\n at clojure.main$main.doInvoke(main.clj:427)\n   at clojure.lang.RestFn.invoke(RestFn.java:457)\n    at clojure.lang.Var.invoke(Var.java:427)\n  at clojure.lang.AFn.applyToHelper(AFn.java:172)\n   at clojure.lang.Var.applyTo(Var.java:532)\n at clojure.main.main(main.java:37)\n;;; Bootstrapping bundled version of SLIME; please wait...\n\n\njava.lang.IllegalArgumentException: No implementation of method: :make-reader of protocol: #'clojure.java.io/IOFactory found for class: nil\n   at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:527)\n   at clojure.java.io$fn__8239$G__8234__8246.invoke(io.clj:73)\n   at clojure.java.io$reader.doInvoke(io.clj:106)\n    at clojure.lang.RestFn.invoke(RestFn.java:410)\n    at clojure.lang.AFn.applyToHelper(AFn.java:161)\n   at clojure.lang.RestFn.applyTo(RestFn.java:132)\n   at clojure.core$apply.invoke(core.clj:603)\n    at clojure.core$slurp.doInvoke(core.clj:6126)\n at clojure.lang.RestFn.invoke(RestFn.java:410)\n    at leiningen.ritz_in$hex_digest.invoke(ritz_in.clj:20)\n    at leiningen.ritz_in$loader.invoke(ritz_in.clj:24)\n    at clojure.core$map$fn__4087.invoke(core.clj:2434)\n    at clojure.lang.LazySeq.sval(LazySeq.java:42)\n at clojure.lang.LazySeq.seq(LazySeq.java:60)\n  at clojure.lang.Cons.next(Cons.java:39)\n   at clojure.lang.LazySeq.next(LazySeq.java:92)\n at clojure.lang.RT.next(RT.java:587)\n  at clojure.core$next.invoke(core.clj:64)\n  at clojure.string$join.invoke(string.clj:138)\n at leiningen.ritz_in$ritz_in.invoke(ritz_in.clj:53)\n   at clojure.lang.Var.invoke(Var.java:419)\n  at clojure.lang.AFn.applyToHelper(AFn.java:163)\n   at clojure.lang.Var.applyTo(Var.java:532)\n at clojure.core$apply.invoke(core.clj:603)\n    at leiningen.core.main$resolve_task$fn__823.doInvoke(main.clj:73)\n at clojure.lang.RestFn.applyTo(RestFn.java:139)\n   at clojure.lang.AFunction$1.doInvoke(AFunction.java:29)\n   at clojure.lang.RestFn.applyTo(RestFn.java:137)\n   at clojure.core$apply.invoke(core.clj:603)\n    at leiningen.core.main$apply_task.invoke(main.clj:95)\n at leiningen.core.main$_main$fn__862.invoke(main.clj:156)\n at leiningen.core.main$_main.doInvoke(main.clj:155)\n   at clojure.lang.RestFn.invoke(RestFn.java:421)\n    at clojure.lang.Var.invoke(Var.java:419)\n  at clojure.lang.AFn.applyToHelper(AFn.java:163)\n   at clojure.lang.Var.applyTo(Var.java:532)\n at clojure.core$apply.invoke(core.clj:601)\n    at clojure.main$main_opt.invoke(main.clj:324)\n at clojure.main$main.doInvoke(main.clj:427)\n   at clojure.lang.RestFn.invoke(RestFn.java:457)\n    at clojure.lang.Var.invoke(Var.java:427)\n  at clojure.lang.AFn.applyToHelper(AFn.java:172)\n   at clojure.lang.Var.applyTo(Var.java:532)\n at clojure.main.main(main.java:37)\n;;; Bootstrapping bundled version of SLIME; please wait...\n\n\njava.lang.IllegalArgumentException: No implementation of method: :make-reader of protocol: #'clojure.java.io/IOFactory found for class: nil\n   at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:527)\n   at clojure.java.io$fn__8239$G__8234__8246.invoke(io.clj:73)\n   at clojure.java.io$reader.doInvoke(io.clj:106)\n    at clojure.lang.RestFn.invoke(RestFn.java:410)\n    at clojure.lang.AFn.applyToHelper(AFn.java:161)\n   at clojure.lang.RestFn.applyTo(RestFn.java:132)\n   at clojure.core$apply.invoke(core.clj:603)\n    at clojure.core$slurp.doInvoke(core.clj:6126)\n at clojure.lang.RestFn.invoke(RestFn.java:410)\n    at leiningen.ritz_in$hex_digest.invoke(ritz_in.clj:20)\n    at leiningen.ritz_in$loader.invoke(ritz_in.clj:24)\n    at clojure.core$map$fn__4087.invoke(core.clj:2434)\n    at clojure.lang.LazySeq.sval(LazySeq.java:42)\n at clojure.lang.LazySeq.seq(LazySeq.java:60)\n  at clojure.lang.Cons.next(Cons.java:39)\n   at clojure.lang.LazySeq.next(LazySeq.java:92)\n at clojure.lang.RT.next(RT.java:587)\n  at clojure.core$next.invoke(core.clj:64)\n  at clojure.string$join.invoke(string.clj:138)\n at leiningen.ritz_in$ritz_in.invoke(ritz_in.clj:53)\n   at clojure.lang.Var.invoke(Var.java:419)\n  at clojure.lang.AFn.applyToHelper(AFn.java:163)\n   at clojure.lang.Var.applyTo(Var.java:532)\n at clojure.core$apply.invoke(core.clj:603)\n    at leiningen.core.main$resolve_task$fn__823.doInvoke(main.clj:73)\n at clojure.lang.RestFn.applyTo(RestFn.java:139)\n   at clojure.lang.AFunction$1.doInvoke(AFunction.java:29)\n   at clojure.lang.RestFn.applyTo(RestFn.java:137)\n   at clojure.core$apply.invoke(core.clj:603)\n    at leiningen.core.main$apply_task.invoke(main.clj:95)\n at leiningen.core.main$_main$fn__862.invoke(main.clj:156)\n at leiningen.core.main$_main.doInvoke(main.clj:155)\n   at clojure.lang.RestFn.invoke(RestFn.java:421)\n    at clojure.lang.Var.invoke(Var.java:419)\n  at clojure.lang.AFn.applyToHelper(AFn.java:163)\n   at clojure.lang.Var.applyTo(Var.java:532)\n at clojure.core$apply.invoke(core.clj:601)\n    at clojure.main$main_opt.invoke(main.clj:324)\n at clojure.main$main.doInvoke(main.clj:427)\n   at clojure.lang.RestFn.invoke(RestFn.java:457)\n    at clojure.lang.Var.invoke(Var.java:427)\n  at clojure.lang.AFn.applyToHelper(AFn.java:172)\n   at clojure.lang.Var.applyTo(Var.java:532)\n at clojure.main.main(main.java:37)\n")
  clojure-jack-in-sentinel(#<process swank> "exited abnormally with code 1\n")
```

`lein ritz-in 4004` won't work, neither.

And here is my profile.clj
https://github.com/cola-zero/cola-zero-dotfiles/blob/master/lein/profiles.clj

**Comment by hugoduncan** [comment]
I'll take a look. Independently of this, I think slime-ritz.el should probably define slime-ritz-jack-in, which should parallel clojure-jack-in and use slime-ritz-swank-command with a sane default configuration, so you don't have to mess with setting clojure-swank-command.

**Comment by cola-zero** [comment]
Thank you. This problem is not critical for me, because `lein ritz` and `M-x slime-connect` work fine now. But I hope jack-in work fine too :)
