### ISSUE TITLE
`lein ritz-nrepl' leads to "VM initialization failed"

### ISSUE THREAD

**Issue by lnostdal** [pallet/ritz#58]
Stuck with nothing working since swank-clojure is deprecated (doesn't run with latest Clojure) and plain nrepl + nrepl.el is pretty non-usable I'm trying out ritz, but:

```
$ lein ritz-nrepl
...
Exception in thread "main" com.sun.jdi.connect.VMStartException: VM initialization failed for: /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java -Xdebug -Xrunjdwp:transport=dt_socket,address=439697:48939,suspend=y -cp ...

 (clojure.core/deref (clojure.core/promise)))
        at com.sun.tools.jdi.AbstractLauncher$Helper.launchAndAccept(AbstractLauncher.java:192)
        at com.sun.tools.jdi.AbstractLauncher.launch(AbstractLauncher.java:132)
        at com.sun.tools.jdi.SunCommandLineLauncher.launch(SunCommandLineLauncher.java:235)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
        at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)
        at ritz.jpda.jdi$launch.invoke(jdi.clj:80)
        at ritz.jpda.jdi_vm$launch_vm.doInvoke(jdi_vm.clj:199)
        at clojure.lang.RestFn.invoke(RestFn.java:425)
        at ritz.nrepl$start_jpda_server.invoke(nrepl.clj:262)
        at user$eval5055.invoke(NO_SOURCE_FILE:1)
        at clojure.lang.Compiler.eval(Compiler.java:6603)
        at clojure.lang.Compiler.eval(Compiler.java:6592)
        at clojure.lang.Compiler.eval(Compiler.java:6593)
        at clojure.lang.Compiler.eval(Compiler.java:6566)
        at clojure.core$eval.invoke(core.clj:2836)
        at clojure.main$eval_opt.invoke(main.clj:297)
        at clojure.main$initialize.invoke(main.clj:316)
        at clojure.main$null_opt.invoke(main.clj:349)
        at clojure.main$main$fn__6714.invoke(main.clj:427)
        at clojure.main$main.doInvoke(main.clj:424)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at clojure.lang.Var.invoke(Var.java:419)
        at clojure.lang.AFn.applyToHelper(AFn.java:163)
        at clojure.lang.Var.applyTo(Var.java:532)
        at clojure.main.main(main.java:37)

```

**Comment by hugoduncan** [comment]
What operating system is this? Which version of ritz?

**Comment by thirteen37** [comment]
I'm seeing this on nrepl-ritz 0.7.0 on Linux.

```
$ java -version
java version "1.7.0_40"
OpenJDK Runtime Environment (IcedTea 2.4.1) (ArchLinux build 7.u40_2.4.1-3-x86_64)
OpenJDK 64-Bit Server VM (build 24.0-b50, mixed mode)
```

**Comment by darth10** [comment]
I used to have this problem as well.
Solved it by switching to Oracle JDK 7.

Worth a shot though.
