### ISSUE TITLE
Nrepl-ritz fails to start on Windows (Create Process Error)

### ISSUE THREAD

**Issue by mebaran** [pallet/ritz#90]
Compiling ClojureScript.  
Exception in thread "main" java.io.IOException: Cannot run program "C:\Program": CreateProcess error=2, The system cannot find the file specified  
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1042)  
        at java.lang.Runtime.exec(Runtime.java:615)  
        at java.lang.Runtime.exec(Runtime.java:483)  
        at com.sun.tools.jdi.AbstractLauncher$Helper.launchAndAccept(AbstractLauncher.java:180)  
        at com.sun.tools.jdi.AbstractLauncher.launch(AbstractLauncher.java:132)  
        at com.sun.tools.jdi.SunCommandLineLauncher.launch(SunCommandLineLauncher.java:235)  
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)  
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
        at java.lang.reflect.Method.invoke(Method.java:601)  
        at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)  
        at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)  
        at ritz.jpda.jdi$launch.invoke(jdi.clj:86)  
        at ritz.jpda.jdi_vm$launch_vm.invoke(jdi_vm.clj:176)  
        at ritz.jpda.debug$launch_vm.invoke(debug.clj:59)  
        at ritz.nrepl$start_jpda_server.invoke(nrepl.clj:259)  
        at user$eval5044.invoke(NO_SOURCE_FILE:1)  
        at clojure.lang.Compiler.eval(Compiler.java:6511)  
        at clojure.lang.Compiler.eval(Compiler.java:6500)  
        at clojure.lang.Compiler.eval(Compiler.java:6501)  
        at clojure.lang.Compiler.eval(Compiler.java:6477)  
        at clojure.core$eval.invoke(core.clj:2797)  
        at clojure.main$eval_opt.invoke(main.clj:297)  
        at clojure.main$initialize.invoke(main.clj:316)  
        at clojure.main$null_opt.invoke(main.clj:349)  
        at clojure.main$main.doInvoke(main.clj:427)  
        at clojure.lang.RestFn.invoke(RestFn.java:421)  
        at clojure.lang.Var.invoke(Var.java:419)  
        at clojure.lang.AFn.applyToHelper(AFn.java:163)  
        at clojure.lang.Var.applyTo(Var.java:532)  
        at clojure.main.main(main.java:37)  
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified 
        at java.lang.ProcessImpl.create(Native Method)  
        at java.lang.ProcessImpl.<init>(ProcessImpl.java:288)  
        at java.lang.ProcessImpl.start(ProcessImpl.java:133)  
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1023)  
        ... 30 more

**Comment by mebaran** [comment]
I think this bug has something to do with this change on Java 7u21 (from changelog: http://www.oracle.com/technetwork/java/javase/7u21-relnotes-1932873.html)

#### Changes to Runtime.exec

On Windows platform, the decoding of command strings specified to Runtime.exec(String), Runtime.exec(String,String[]) and Runtime.exec(String,String[],File) methods, has been improved to follow the specification more closely. This may cause problems for applications that are using one or more of these methods with commands that contain spaces in the program name, or are invoking these methods with commands that are not quoted correctly.

For example, Runtime.getRuntime().exec("C:\My Programs\foo.exe bar") is an attempt to launch the program "C:\My" with the arguments "Programs\foo.exe" and "bar". This command is likely to fail with an exception to indicate "C:\My" cannot be found.

The example Runtime.getRuntime().exec("\"C:\My Programs\foo.exe\" bar") is an attempt to launch the program "\"C:\My". This command will fail with an exception to indicate the program has an embedded quote.

Applications that need to launch programs with spaces in the program name should consider using the variants of Runtime.exec that allow the command and arguments to be specified in an array.

Alternatively, the preferred way to create operating systems processes since JDK 5.0 is using java.lang.ProcessBuilder. The ProcessBuilder class has a much more complete API for setting the environment, working directory and redirecting streams for the process.

---

Any possible work around?  It looks like the .launch method may simply be broken on this release on Windows.  I have confirmed this by getting it to work on Java 7u17 as opposed to 7u21.
