### ISSUE TITLE
VMStartException when running lein ritz-nrepl on 0.7.0

### ISSUE THREAD

**Issue by cdorrat** [pallet/ritz#99]
When running `lein ritz-nrepl` with v "0.7.0" from clojars I'm getting a VMStartException on startup.

Running `lein ritz` or `lein ritz-in` seems to work ok, it's just reitz-nrepl that's failing.
I'm running OpenJDK 7 on Ubuntu 12.04
package: openjdk-7-jdk 7u21-2.3.9-0ubuntu0.12.04.1

java -version gives:
  java version "1.7.0_21"
  OpenJDK Runtime Environment (IcedTea 2.3.9) (7u21-2.3.9-0ubuntu0.12.04.1)
  OpenJDK 64-Bit Server VM (build 23.7-b01, mixed mode)

I've tried both of the following Leineningen versions:
- Leiningen 2.1.2 on Java 1.7.0_21 OpenJDK 64-Bit Server VM<
- Leiningen 2.2.0 on Java 1.7.0_21 OpenJDK 64-Bit Server VM

My .lein/profile has the following lines:

```
{:plugins [[lein-cljsbuild "0.2.10"]
                  [lein-ritz "0.7.0"]]
        :dependencies [[nrepl-inspect "0.3.0"]
                        [gui-diff "0.6.0"]
                        [slamhound "1.3.3"]
                        [org.clojure/tools.trace "0.7.5"]
                        [javert "0.2.0-SNAPSHOT"]
                        [ritz/ritz-nrepl-middleware "0.7.0"]]
        :repl-options {:nrepl-middleware
                       [inspector.middleware/wrap-inspect]}}
```

The stack trace is:
Exception in thread "main" com.sun.jdi.connect.VMStartException: VM initialization failed for: /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java -Xdebug -Xrunjdwp:transport=dt_socket,address=discordia.dorrat.com:38548,suspend=y -cp /home/cnd/src/clojure/my-test/src/test/clojure:/home/cnd/src/clojure/my-test/src/main/clojure:/home/cnd/src/clojure/my-test/dev-resources:/home/cnd/src/clojure/my-test/resources:/home/cnd/src/clojure/my-test/target/classes:/home/cnd/.m2/repository/com/googlecode/netlib-java/netlib-java/0.9.3/netlib-java-0.9.3.jar:/home/cnd/.m2/repository/midje/midje/1.4.0/midje-1.4.0.jar:/home/cnd/.m2/repository/org/apache/geronimo/specs/geronimo-jta_1.0.1B_spec/1.0/geronimo-jta_1.0.1B_spec-1.0.jar:/home/cnd/.m2/repository/org/apache/geronimo/specs/geronimo-ejb_2.1_spec/1.0/geronimo-ejb_2.1_spec-1.0.jar:/home/cnd/.m2/repository/com/google/code/findbugs/jsr305/1.3.9/jsr305-1.3.9.jar:/home/cnd/.m2/repository/org/apache/geronimo/specs/geronimo-servlet_2.4_spec/1.0/geronimo-servlet_2.4_spec-1.0.jar:/home/cnd/.m2/repository/org/tcrawley/dynapath/0.2.1/dynapath-0.2.1.jar:/home/cnd/.m2/repository/nl/knaw/dans/common/dans-dbf-lib/1.0.0-beta-10/dans-dbf-lib-1.0.0-beta-10.jar:/home/cnd/.m2/repository/javax/servlet/servlet-api/2.3/servlet-api-2.3.jar:/home/cnd/.m2/repository/org/swinglabs/swingx/swingx-painters/1.6.3/swingx-painters-1.6.3.jar:/home/cnd/.m2/repository/javert/javert/0.2.0-SNAPSHOT/javert-0.2.0-SNAPSHOT.jar:/home/cnd/.m2/repository/useful/useful/0.8.3-alpha8/useful-0.8.3-alpha8.jar:/home/cnd/.m2/repository/org/clojure/java.classpath/0.2.0/java.classpath-0.2.0.jar:/home/cnd/.m2/repository/me/raynes/fs/1.4.0/fs-1.4.0.jar:/home/cnd/.m2/repository/utilize/utilize/0.2.3/utilize-0.2.3.jar:/home/cnd/.m2/repository/colorize/colorize/0.1.1/colorize-0.1.1.jar:/home/cnd/.m2/repository/gui-diff/gui-diff/0.6.0/gui-diff-0.6.0.jar:/home/cnd/.m2/repository/com/novemberain/monger/1.4.2/monger-1.4.2.jar:/home/cnd/.m2/repository/net/sf/opencsv/opencsv/2.3/opencsv-2.3.jar:/home/cnd/.m2/repository/net/sourceforge/parallelcolt/parallelcolt/0.10.0/parallelcolt-0.10.0.jar:/home/cnd/.m2/repository/junit/junit/4.5/junit-4.5.jar:/home/cnd/.m2/repository/openejb/openejb-loader/1.0/openejb-loader-1.0.jar:/home/cnd/.m2/repository/groovy/groovy/1.0/groovy-1.0.jar:/home/cnd/.m2/repository/commons-httpclient/commons-httpclient/3.0.1/commons-httpclient-3.0.1.jar:/home/cnd/.m2/repository/org/clojars/cdorrat/geva-core/1.2-SNAPSHOT/geva-core-1.2-SNAPSHOT.jar:/home/cnd/.m2/repository/cglib/cglib-full/2.0/cglib-full-2.0.jar:/home/cnd/.m2/repository/commons-collections/commons-collections/3.2/commons-collections-3.2.jar:/home/cnd/.m2/repository/org/pentaho/pentaho-commons/pentaho-package-manager/1.0.6/pentaho-package-manager-1.0.6.jar:/home/cnd/.m2/repository/com/github/rwl/COLAMDJ/1.0.1/COLAMDJ-1.0.1.jar:/home/cnd/.m2/repository/classlojure/classlojure/0.6.6/classlojure-0.6.6.jar:/home/cnd/.m2/repository/backport-util-concurrent/backport-util-concurrent/2.0_01_pd/backport-util-concurrent-2.0_01_pd.jar:/home/cnd/.m2/repository/ritz/ritz-nrepl-middleware/0.7.0/ritz-nrepl-middleware-0.7.0.jar:/home/cnd/.m2/repository/org/clojure/tools.trace/0.7.5/tools.trace-0.7.5.jar:/home/cnd/.m2/repository/org/apache/commons/commons-compress/1.3/commons-compress-1.3.jar:/home/cnd/.m2/repository/regexp/regexp/1.3/regexp-1.3.jar:/home/cnd/.m2/repository/xpp3/xpp3/1.1.3.4.O/xpp3-1.1.3.4.O.jar:/home/cnd/.m2/repository/qdox/qdox/1.5/qdox-1.5.jar:/home/cnd/.m2/repository/net/sourceforge/parallelcolt/optimization/1.0/optimization-1.0.jar:/home/cnd/.m2/repository/axion/axion/1.0-M3-dev/axion-1.0-M3-dev.jar:/home/cnd/.m2/repository/net/sourceforge/csparsej/csparsej/1.1.1/csparsej-1.1.1.jar:/home/cnd/.m2/repository/net/sourceforge/f2j/arpack_combined_all/0.1/arpack_combined_all-0.1.jar:/home/cnd/.m2/repository/radeox/radeox/0.9/radeox-0.9.jar:/home/cnd/.m2/repository/com/github/rwl/BTFJ/1.0.1/BTFJ-1.0.1.jar:/home/cnd/.m2/repository/net/sourceforge/jplasma/jplasma/1.2.0/jplasma-1.2.0.jar:/home/cnd/.m2/repository/net/sourceforge/jplasma/core-lapack/0.1/core-lapack-0.1.jar:/home/cnd/.m2/repository/com/quantisan/clatrix/0.2.2/clatrix-0.2.2.jar:/home/cnd/.m2/repository/org/swinglabs/swingx/swingx-action/1.6.3/swingx-action-1.6.3.jar:/home/cnd/.m2/repository/oro/oro/2.0.8/oro-2.0.8.jar:/home/cnd/.m2/repository/nekohtml/nekohtml/0.9.5/nekohtml-0.9.5.jar:/home/cnd/.m2/repository/com/thoughtworks/xstream/xstream/1.2/xstream-1.2.jar:/home/cnd/.m2/repository/xerces/xercesImpl/2.4.0/xercesImpl-2.4.0.jar:/home/cnd/.m2/repository/asm/asm-tree/2.2/asm-tree-2.2.jar:/home/cnd/.m2/repository/org/clojure/math.combinatorics/0.0.3/math.combinatorics-0.0.3.jar:/home/cnd/.m2/repository/com/github/rwl/JKLU/1.0.0/JKLU-1.0.0.jar:/home/cnd/.m2/repository/com/miglayout/miglayout/3.7.4/miglayout-3.7.4.jar:/home/cnd/.m2/repository/avalon-framework/avalon-framework/4.1.3/avalon-framework-4.1.3.jar:/home/cnd/.m2/repository/logkit/logkit/1.0.1/logkit-1.0.1.jar:/home/cnd/.m2/repository/commons-logging/commons-logging/1.1/commons-logging-1.1.jar:/home/cnd/.m2/repository/bsf/bsf/2.4.0/bsf-2.4.0.jar:/home/cnd/.m2/repository/clj-info/clj-info/0.2.6/clj-info-0.2.6.jar:/home/cnd/.m2/repository/org/clojure/core.incubator/0.1.0/core.incubator-0.1.0.jar:/home/cnd/.m2/repository/org/swinglabs/swingx/swingx-autocomplete/1.6.3/swingx-autocomplete-1.6.3.jar:/home/cnd/.m2/repository/jscheme/jscheme/7.2/jscheme-7.2.jar:/home/cnd/.m2/repository/org/apache/httpcomponents/httpclient/4.2.1/httpclient-4.2.1.jar:/home/cnd/.m2/repository/asm/asm-util/2.2/asm-util-2.2.jar:/home/cnd/.m2/repository/ant/ant-launcher/1.6.5/ant-launcher-1.6.5.jar:/home/cnd/.m2/repository/com/dorrat/jgrapht-ext/0.8.3-SNAPSHOT/jgrapht-ext-0.8.3-SNAPSHOT.jar:/home/cnd/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-smile/2.0.5/jackson-dataformat-smile-2.0.5.jar:/home/cnd/.m2/repository/com/jgoodies/forms/1.2.1/forms-1.2.1.jar:/home/cnd/.m2/repository/asm/asm/2.2/asm-2.2.jar:/home/cnd/.m2/repository/net/java/dev/javacc/javacc/3.2/javacc-3.2.jar:/home/cnd/.m2/repository/clj-http/clj-http/0.5.3/clj-http-0.5.3.jar:/home/cnd/.m2/repository/slingshot/slingshot/0.8.0/slingshot-0.8.0.jar:/home/cnd/.m2/repository/org/apache/httpcomponents/httpcore/4.2.1/httpcore-4.2.1.jar:/home/cnd/.m2/repository/seesaw/seesaw/1.4.2/seesaw-1.4.2.jar:/home/cnd/.m2/repository/org/clojars/trptcolin/sjacket/0.1.3/sjacket-0.1.3.jar:/home/cnd/.m2/repository/clojurewerkz/support/0.10.0/support-0.10.0.jar:/home/cnd/.m2/repository/ant/ant/1.6.5/ant-1.6.5.jar:/home/cnd/.m2/repository/castor/castor/0.9.9.0-pre/castor-0.9.9.0-pre.jar:/home/cnd/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.0.5/jackson-core-2.0.5.jar:/home/cnd/.m2/repository/net/sf/squirrel-sql/thirdparty-non-maven/java-cup/0.11a/java-cup-0.11a.jar:/home/cnd/.m2/repository/slamhound/slamhound/1.3.3/slamhound-1.3.3.jar:/home/cnd/.m2/repository/cheshire/cheshire/4.0.2/cheshire-4.0.2.jar:/home/cnd/.m2/repository/org/apache/geronimo/specs/geronimo-j2ee-connector_1.5_spec/1.0/geronimo-j2ee-connector_1.5_spec-1.0.jar:/home/cnd/.m2/repository/log4j/log4j/1.2.12/log4j-1.2.12.jar:/home/cnd/.m2/repository/clojure-csv/clojure-csv/2.0.0-alpha1/clojure-csv-2.0.0-alpha1.jar:/home/cnd/.m2/repository/org/clojure/tools.macro/0.1.1/tools.macro-0.1.1.jar:/home/cnd/.m2/repository/org/clojure/tools.nrepl/0.2.1/tools.nrepl-0.2.1.jar:/home/cnd/.m2/repository/clj-time/clj-time/0.4.4/clj-time-0.4.4.jar:/home/cnd/.m2/repository/incanter/jcommon/1.0.16/jcommon-1.0.16.jar:/home/cnd/.m2/repository/commons-primitives/commons-primitives/1.0/commons-primitives-1.0.jar:/home/cnd/.m2/repository/jmock/jmock-cglib/1.1.0/jmock-cglib-1.1.0.jar:/home/cnd/.m2/repository/ragtime/ragtime.core/0.3.0/ragtime.core-0.3.0.jar:/home/cnd/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar:/home/cnd/.m2/repository/org/clojure/algo.monads/0.1.0/algo.monads-0.1.0.jar:/home/cnd/.m2/repository/j18n/j18n/1.0.1/j18n-1.0.1.jar:/home/cnd/.m2/repository/commons-codec/commons-codec/1.2/commons-codec-1.2.jar:/home/cnd/.m2/repository/org/jblas/jblas/1.2.2/jblas-1.2.2.jar:/home/cnd/.m2/repository/org/clojure/clojure/1.4.0/clojure-1.4.0.jar:/home/cnd/.m2/repository/org/mongodb/mongo-java-driver/2.10.1/mongo-java-driver-2.10.1.jar:/home/cnd/.m2/repository/nrepl-inspect/nrepl-inspect/0.3.0/nrepl-inspect-0.3.0.jar:/home/cnd/.m2/repository/cglib/cglib-nodep/2.1_3/cglib-nodep-2.1_3.jar:/home/cnd/.m2/repository/org/clojure/tools.logging/0.2.6/tools.logging-0.2.6.jar:/home/cnd/.m2/repository/hiccup/hiccup/1.0.1/hiccup-1.0.1.jar:/home/cnd/.m2/repository/incanter/incanter-core/1.5.0-SNAPSHOT/incanter-core-1.5.0-SNAPSHOT.jar:/home/cnd/.m2/repository/clojure-complete/clojure-complete/0.2.1/clojure-complete-0.2.1.jar:/home/cnd/.m2/repository/dorothy/dorothy/0.0.3/dorothy-0.0.3.jar:/home/cnd/.m2/repository/com/tonicsystems/jarjar/0.6/jarjar-0.6.jar:/home/cnd/.m2/repository/radeox/radeox-oro/0.9/radeox-oro-0.9.jar:/home/cnd/.m2/repository/net/cgrand/regex/1.1.0/regex-1.1.0.jar:/home/cnd/.m2/repository/com/dorrat/jgrapht-core/0.8.3-SNAPSHOT/jgrapht-core-0.8.3-SNAPSHOT.jar:/home/cnd/.m2/repository/jmock/jmock/1.1.0/jmock-1.1.0.jar:/home/cnd/.m2/repository/asm/asm-analysis/2.2/asm-analysis-2.2.jar:/home/cnd/.m2/repository/javax/servlet/jsp-api/2.0/jsp-api-2.0.jar:/home/cnd/.m2/repository/org/swinglabs/swingx/swingx-core/1.6.3/swingx-core-1.6.3.jar:/home/cnd/.m2/repository/org/swinglabs/swingx/swingx-plaf/1.6.3/swingx-plaf-1.6.3.jar:/home/cnd/.m2/repository/ant/ant-junit/1.6.5/ant-junit-1.6.5.jar:/home/cnd/.m2/repository/joda-time/joda-time/2.1/joda-time-2.1.jar:/home/cnd/.m2/repository/mockobjects/mockobjects-core/0.09/mockobjects-core-0.09.jar:/home/cnd/.m2/repository/incanter/incanter-charts/1.5.0-SNAPSHOT/incanter-charts-1.5.0-SNAPSHOT.jar:/home/cnd/.m2/repository/commons-cli/commons-cli/1.0/commons-cli-1.0.jar:/home/cnd/.m2/repository/xpp3/xpp3_min/1.1.3.4.O/xpp3_min-1.1.3.4.O.jar:/home/cnd/.m2/repository/com/novemberain/validateur/1.2.0/validateur-1.2.0.jar:/home/cnd/.m2/repository/net/sourceforge/jtransforms/jtransforms/2.4.0/jtransforms-2.4.0.jar:/home/cnd/.m2/repository/ritz/ritz-debugger/0.7.0/ritz-debugger-0.7.0.jar:/home/cnd/.m2/repository/incanter/jfreechart/1.0.13-no-gnujaxp/jfreechart-1.0.13-no-gnujaxp.jar:/home/cnd/.m2/repository/mx4j/mx4j/3.0.1/mx4j-3.0.1.jar:/home/cnd/.m2/repository/clj-ns-browser/clj-ns-browser/1.3.0/clj-ns-browser-1.3.0.jar:/home/cnd/.m2/repository/openejb/openejb-core/1.0/openejb-core-1.0.jar:/home/cnd/.m2/repository/xml-apis/xml-apis/1.0.b2/xml-apis-1.0.b2.jar:/home/cnd/.m2/repository/antlr/antlr/2.7.5/antlr-2.7.5.jar:/home/cnd/.m2/repository/com/taoensso/nippy/1.2.1/nippy-1.2.1.jar:/home/cnd/.m2/repository/jgraph/jgraph/5.13.0.0/jgraph-5.13.0.0.jar:/home/cnd/.m2/repository/com/github/rwl/AMDJ/1.0.1/AMDJ-1.0.1.jar:/home/cnd/.m2/repository/idb/idb/3.26/idb-3.26.jar:/home/cnd/.m2/repository/org/apache/httpcomponents/httpmime/4.2.1/httpmime-4.2.1.jar:/home/cnd/.m2/repository/com/google/guava/guava/12.0/guava-12.0.jar:/home/cnd/.m2/repository/org/clojure/tools.namespace/0.2.3/tools.namespace-0.2.3.jar:/home/cnd/.m2/repository/org/fife/ui/rsyntaxtextarea/2.0.3/rsyntaxtextarea-2.0.3.jar:/home/cnd/.m2/repository/org/apache/bsf/bsf-api/3.1/bsf-api-3.1.jar:/home/cnd/.m2/repository/org/clojure/tools.cli/0.2.2/tools.cli-0.2.2.jar:/home/cnd/.m2/repository/ritz/ritz-nrepl/0.7.0/ritz-nrepl-0.7.0.jar:/home/cnd/.m2/repository/org/clojure/core.unify/0.5.2/core.unify-0.5.2.jar:/home/cnd/.m2/repository/commons-lang/commons-lang/1.0/commons-lang-1.0.jar:/home/cnd/.m2/repository/incanter/incanter-io/1.5.0-SNAPSHOT/incanter-io-1.5.0-SNAPSHOT.jar:/home/cnd/.m2/repository/ritz/ritz-repl-utils/0.7.0/ritz-repl-utils-0.7.0.jar:/home/cnd/.m2/repository/org/danlarkin/clojure-json/1.1/clojure-json-1.1.jar:/home/cnd/.m2/repository/net/mikera/clojure-utils/0.2.1/clojure-utils-0.2.1.jar:/home/cnd/.m2/repository/ordered/ordered/1.2.0/ordered-1.2.0.jar:/home/cnd/.m2/repository/swiss-arrows/swiss-arrows/0.1.0/swiss-arrows-0.1.0.jar:/home/cnd/.m2/repository/nz/ac/waikato/cms/weka/weka-dev/3.7.9/weka-dev-3.7.9.jar:/home/cnd/.m2/repository/org/thnetos/cd-client/0.3.5/cd-client-0.3.5.jar:/home/cnd/.m2/repository/org/iq80/snappy/snappy/0.3/snappy-0.3.jar:/home/cnd/.m2/repository/net/cgrand/parsley/0.9.1/parsley-0.9.1.jar:/home/cnd/.m2/repository/org/swinglabs/swingx/swingx-common/1.6.3/swingx-common-1.6.3.jar:/home/cnd/.m2/repository/asm/asm-attrs/2.2/asm-attrs-2.2.jar:/usr/lib/jvm/java-7-openjdk-amd64/lib/tools.jar:/usr/lib/jvm/java-7-openjdk-amd64/lib/sa-jdi.jar clojure.main -i /tmp/ritz-init1375551880235411624.clj
    at com.sun.tools.jdi.AbstractLauncher$Helper.launchAndAccept(AbstractLauncher.java:192)
    at com.sun.tools.jdi.AbstractLauncher.launch(AbstractLauncher.java:132)
    at com.sun.tools.jdi.SunCommandLineLauncher.launch(SunCommandLineLauncher.java:235)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
    at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)
    at ritz.jpda.jdi$launch.invoke(jdi.clj:86)
    at ritz.jpda.jdi_vm$launch_vm.invoke(jdi_vm.clj:176)
    at ritz.jpda.debug$launch_vm.invoke(debug.clj:59)
    at ritz.nrepl$start_jpda_server.invoke(nrepl.clj:259)
    at user$eval5325.invoke(NO_SOURCE_FILE:1)
    at clojure.lang.Compiler.eval(Compiler.java:6511)
    at clojure.lang.Compiler.eval(Compiler.java:6500)
    at clojure.lang.Compiler.eval(Compiler.java:6501)
    at clojure.lang.Compiler.eval(Compiler.java:6477)
    at clojure.core$eval.invoke(core.clj:2797)
    at clojure.main$eval_opt.invoke(main.clj:297)
    at clojure.main$initialize.invoke(main.clj:316)
    at clojure.main$null_opt.invoke(main.clj:349)
    at clojure.main$main.doInvoke(main.clj:427)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at clojure.lang.Var.invoke(Var.java:419)
    at clojure.lang.AFn.applyToHelper(AFn.java:163)
    at clojure.lang.Var.applyTo(Var.java:532)
    at clojure.main.main(main.java:37)

The clj file created in /tmp has the following contents:

```
(do (clojure.core/let [thread__2106__auto__ (java.lang.Thread. 
                                             (clojure.core/fn [] 
                                               (java.lang.Thread/sleep 1000) 
                                               (throw (java.lang.Exception. "JDI-VM-Control-Thread"))))] 
      (.setName thread__2106__auto__ 
                (clojure.core/str (quote JDI-VM-Control-Thread))) 
      (.setDaemon thread__2106__auto__ false) 
      (.start thread__2106__auto__) nil) 
    (clojure.core/deref (clojure.core/promise)))
```

**Comment by coventry** [comment]
I'm seeing this error, too.  Also on ubuntu 12.04, but with openjdk-6-jdk.  It was working fine, then started giving this error message after the virtual machine it was running on  was rebooted.  On the same machine, it gives this error message even with a fresh install of leiningen in a fresh account, and the following in profiles.clj:

{:user {:plugins [[lein-ritz "0.7.0"]]
        :dependencies [[nrepl-inspect "0.3.0"]
                       [ritz/ritz-nrepl-middleware "0.7.0"]
                       [ritz/ritz-debugger "0.7.0"]]
        :repl-options
        {:nrepl-middleware
         [inspector.middleware/wrap-inspect
          ritz.nrepl.middleware.javadoc/wrap-javadoc
          ritz.nrepl.middleware.apropos/wrap-apropos]}}}

The project directory I ran it from was freshly created with "lein new."
